on:
  workflow_dispatch:
jobs:
    pyinstaller-build:
      runs-on: <windows-latest / ubuntu-latest / macos-latest>
      steps:
        - name: Create Executable
          uses: sayyid5416/pyinstaller@v1
          with:
            python_ver: '3.6'
            spec: 'main.py'
            requirements: 'src/requirements.txt'
            upload_exe_with_name: 'Plug Hero'
            options: --onefile, --name "Plug Hero", --windowed, 
